name: Terraform Init Only

on:
  workflow_dispatch:  # 수동 실행

jobs:
  terraform-init:
    name: Terraform Init for Backend
    runs-on: ubuntu-latest

    permissions:
      id-token: write
      contents: read

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Configure AWS credentials (OIDC)
        uses: aws-actions/configure-aws-credentials@v2
        with:
          role-to-assume: arn:aws:iam::723165663216:role/github-actions-terraform-role
          aws-region: ap-northeast-2

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.7.5

      - name: Terraform Init Only
        run: terraform -chdir=infra/dr_terraform/envs init

